### PR TITLE
update plugin to latest working APIs

### PR DESCRIPTION
**Pull request by senadir**
This PR updates the whole repo to the latest working code, taking from automateWoo/MailPoet and our new APIs. The previous version didn't provide a good integration standard.

Next point we should provide more docs.

### CODE REVIEW

**Review by opr — COMMENTED** [review]
This isn't working, it looks like the scripts aren't being loaded in the editor.

I think we need to wait for the `woocommerce_blocks_loaded` action before running the code in `newsletter-test.php`, and also register the `newsletter-test.js` script in the editor.

```patch
diff --git a/newsletter-test.php b/newsletter-test.php
index 4e44444..30f9ba9 100644
--- a/newsletter-test.php
+++ b/newsletter-test.php
@@ -17,26 +17,27 @@
  * License: GNU General Public License v3.0
  * License URI: https://www.gnu.org/licenses/gpl-3.0.html
  */
+add_action( 'woocommerce_blocks_loaded', function() {
+	define( 'NEWSLETTER_VERSION', '2.0.0' );
+	if ( class_exists( '\Automattic\WooCommerce\Blocks\Package' ) ) {
+		require dirname( __FILE__ ) . '/woocommerce-blocks-integration.php';
+		add_action(
+			'woocommerce_blocks_checkout_block_registration',
+			function( $integration_registry ) {
+				$integration_registry->register( new Newsletter_Blocks_Integration() );
+			},
+			10,
+			1
+		);
 
-define( 'NEWSLETTER_VERSION', '2.0.0' );
-if ( class_exists( '\Automattic\WooCommerce\Blocks\Package' ) ) {
-	require dirname( __FILE__ ) . '/woocommerce-blocks-integration.php';
-	add_action(
-		'woocommerce_blocks_checkout_block_registration',
-		function( $integration_registry ) {
-			$integration_registry->register( new Newsletter_Blocks_Integration() );
-		},
-		10,
-		1
-	);
-
-	add_action(
-		'woocommerce_blocks_checkout_update_order_from_request',
-		function( $order, $request ) {
-			$optin = $request['extensions']['automatewoo'][ 'optin' ];
-			// your logic
-		},
-		10,
-		2
-	);
-}
\ No newline at end of file
+		add_action(
+			'woocommerce_blocks_checkout_update_order_from_request',
+			function( $order, $request ) {
+				$optin = $request['extensions']['automatewoo'][ 'optin' ];
+				// your logic
+			},
+			10,
+			2
+		);
+	}
+});
\ No newline at end of file
diff --git a/woocommerce-blocks-integration.php b/woocommerce-blocks-integration.php
index 3ea0ab3..0017647 100644
--- a/woocommerce-blocks-integration.php
+++ b/woocommerce-blocks-integration.php
@@ -29,6 +29,7 @@ class Newsletter_Blocks_Integration implements IntegrationInterface {
 	 */
 	public function initialize() {
 		$this->register_frontend_scripts();
+		$this->register_editor_scripts();
 		$this->register_editor_blocks();
 		$this->extend_store_api();
 		add_filter( '__experimental_woocommerce_blocks_add_data_attributes_to_block', [ $this, 'add_attributes_to_frontend_blocks' ], 10, 1 );
@@ -58,6 +59,31 @@ class Newsletter_Blocks_Integration implements IntegrationInterface {
 			dirname( __FILE__ ) . '/languages'
 		);
 	}
+
+	public function register_editor_scripts() {
+		$script_path       = '/build/newsletter-block.js';
+		$script_url        = plugins_url( $script_path, __FILE__ );
+		$script_asset_path = dirname( __FILE__ ) . '/build/newsletter-block.asset.php';
+		$script_asset      = file_exists( $script_asset_path )
+			? require $script_asset_path
+			: array(
+				'dependencies' => array(),
+				'version'      => $this->get_file_version( $script_asset_path ),
+			);
+
+		wp_register_script(
+			'newsletter-test-editor',
+			$script_url,
+			$script_asset['dependencies'],
+			$script_asset['version'],
+			true
+		);
+		wp_set_script_translations(
+			'newsletter-test-editor', // script handle
+			'newsletter-test', // text domain
+			dirname( __FILE__ ) . '/languages'
+		);
+	}
 	/**
 	 * Returns an array of script handles to enqueue in the frontend context.
 	 *
@@ -73,7 +99,7 @@ class Newsletter_Blocks_Integration implements IntegrationInterface {
 	 * @return string[]
 	 */
 	public function get_editor_script_handles() {
-		return array();
+		return array( 'newsletter-test-editor' );
 	}
 
 	/**
```

**Comment by senadir** [comment]
@opr this is similar to a commit that Mike pushed in #6, except he used `plugin_loaded` instead of `woocommerce_blocks_loaded` which is a bit earlier and a bit better here?
https://github.com/woocommerce/newsletter-test/pull/6/commits/49487f001221e4ca83232554e89c448f737074d6

**Review by opr — APPROVED** [review]
Works OK, but we're not supposed to be doing anything with the value of the checkbox after placing the order, right? Like not adding it to order meta or anything like that?

**Comment by senadir** [comment]
> Works OK, but we're not supposed to be doing anything with the value of the checkbox after placing the order, right? Like not adding it to order meta or anything like that?

No, we just have a comment "plug your code here" but that's it.

**Pull request merged**
